layout_spectrum: 0.2397799
color:
  saturation: 0.1543446
  lightness: 0.5926144
  brandStrength: 0.6503837
  brandColors:
    - '#FEFEFE'
    - '#39516B'
    - '#0F1315'
    - '#A0ACC0'
    - '#648338'
  rhythmicContrast: 0.6078123
typography_spectrum: 0.07490042
name: Checkpoint 103
